apiVersion: v1 
kind: Service
metadata:
  name: my-service
  labels:
    name: my-service
    app: libera-port
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: my-server